#!/usr/bin/env python3
import json
import os
import platform
import statistics
from collections import defaultdict
from pathlib import Path


def get_system_specs() -> dict[str, str]:
    return {
        "OS": f"{platform.system()} {platform.release()}",
        "Architecture": platform.machine(),
        "CPU": platform.processor() or "unknown",
        "Python": platform.python_version(),
        "Cores": str(os.cpu_count() or "unknown"),
    }


def normalize_row(row: dict) -> dict:
    params = row.get("parameters", {})
    stats = row.get("stats", {})
    return {
        "language": row.get("language", ""),
        "backend": row.get("backend", ""),
        "benchmark": row.get("benchmark", ""),
        **{f"param.{k}": v for k, v in params.items()},
        "mean_ms": stats.get("mean", 0.0),
        "stddev_ms": stats.get("stddev", 0.0),
        "iterations": stats.get("iterations", 0),
    }


def markdown_table(rows: list[dict], columns: list[str]) -> str:
    header = "| " + " | ".join(columns) + " |"
    sep = "|" + "|".join(["---" for _ in columns]) + "|"
    body = []
    for row in rows:
        vals = []
        for col in columns:
            val = row.get(col, "")
            if isinstance(val, float):
                vals.append(f"{val:.4f}")
            else:
                vals.append(str(val))
        body.append("| " + " | ".join(vals) + " |")
    return "\n".join([header, sep, *body])


def write_report(results: list[dict], out_path: Path) -> None:
    normalized = [normalize_row(r) for r in results]

    grouped: dict[str, list[dict]] = defaultdict(list)
    for row in normalized:
        grouped[row["benchmark"]].append(row)

    with open(out_path, "w") as f:
        f.write("This file is automatically generated by benchmark CI.\n\n")
        f.write("## System Specifications\n\n")
        for k, v in get_system_specs().items():
            f.write(f"- **{k}:** {v}\n")
        f.write("\n")

        for benchmark in sorted(grouped.keys()):
            rows = sorted(grouped[benchmark], key=lambda r: (r["language"], r["backend"]))
            f.write(f"### {benchmark.capitalize()} Benchmark\n\n")

            param_cols = sorted({k for row in rows for k in row.keys() if k.startswith("param.")})
            cols = ["language", "backend", *param_cols, "mean_ms", "stddev_ms", "iterations"]
            f.write(markdown_table(rows, cols))
            f.write("\n\n")

        comparisons: dict[tuple, list[float]] = defaultdict(list)
        for row in normalized:
            key = (row["benchmark"], row.get("param.ngram_size"), row.get("param.threshold"))
            comparisons[key].append(row["mean_ms"])

        all_means = [statistics.mean(v) for v in comparisons.values() if v]
        if all_means:
            f.write("## Aggregate\n\n")
            f.write(f"- Mean of benchmark means: {statistics.mean(all_means):.4f} ms\n")


def main() -> None:
    benches_dir = Path(__file__).resolve().parent
    results_path = benches_dir / "results.json"
    report_path = benches_dir.parent / "BENCHMARKS.md"

    if not results_path.exists():
        raise SystemExit(f"results.json not found: {results_path}")

    with open(results_path) as f:
        data = json.load(f)

    if not isinstance(data, list):
        raise SystemExit("results.json must contain a list")

    write_report(data, report_path)
    print(f"Wrote benchmark report: {report_path}")


if __name__ == "__main__":
    main()
